package/objects/Episode__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Episode_Name__c</fullName>
        <inlineHelpText>The name of episode</inlineHelpText>
        <label>Episode Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Episodes</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TV_Serie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TV Serie</label>
        <referenceTo>TV_Serie__c</referenceTo>
        <relationshipLabel>Episodes</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Episode</label>
    <nameField>
        <displayFormat>Episode-{0000}</displayFormat>
        <label>Episode Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

package/objects/Review__c.object
<CustomObject>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TV_Serie__c</fullName>
        <label>TV Serie</label>
        <referenceTo>TV_Serie__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review</label>
    <nameField>
        <displayFormat>review-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

package/objects/Season__c.object
<CustomObject>
    <fields>
        <fullName>Sesaon_Name__c</fullName>
        <inlineHelpText>example Season 1</inlineHelpText>
        <label>Sesaon Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TV_Serie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>TV Serie</label>
        <referenceTo>TV_Serie__c</referenceTo>
        <relationshipLabel>Seasons</relationshipLabel>
        <relationshipName>Seasons</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Season</label>
    <nameField>
        <displayFormat>season-{0000}</displayFormat>
        <label>Season Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

package/objects/TV_Serie__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Logo_url__c</fullName>
        <label>Logo_url</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <formula>Rating_sum__c / Reviews__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Rating</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Year_of_production__c</fullName>
        <label>Year_of_production</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>TV Serie</label>
    <nameField>
        <label>TV Serie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public with sharing class TestDataFactory {

    public static Episode__c getSimpleEpisode(String name, Id season, String description) {
        Episode__c episode = new Episode__c();
        episode.Episode_Name__c = name;
        episode.Season__c = season;
        episode.Description__c = description;
        return episode;
    }

    public static Review__c getSimpleReview(Integer rating, Id tvserie) {
        Review__c review = new Review__c();
        review.Rating__c = rating;
        review.TV_Serie__c = tvserie;
        return review;
    }

    public static Season__c getSimpleSeason(String name, Id tvserie) {
        Season__c season = new Season__c();
        season.Sesaon_Name__c = name;
        season.TV_Serie__c = tvserie;
        return season;
    }

    public static TV_Serie__c getSimpleTvSerie(String name,String url, String description) {
        TV_Serie__c tvserie = new TV_Serie__c();
        tvserie.Name = name;
        tvserie.Logo_url__c = url;
        tvserie.Description__c = description;
        tvserie.Year_of_production__c = '1999';
        return tvserie;
    }
}