package/objects/Episode__c.object
<CustomObject>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Episodes</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TV_Serie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TV Serie</label>
        <referenceTo>TV_Serie__c</referenceTo>
        <relationshipLabel>Episodes</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Episode</label>
    <nameField>
        <displayFormat>Episode-{0000}</displayFormat>
        <label>Episode Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

package/objects/Review__c.object
<CustomObject>
    <fields>
        <fullName>TV_Serie__c</fullName>
        <label>TV Serie</label>
        <referenceTo>TV_Serie__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review</label>
    <nameField>
        <displayFormat>review-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

package/objects/Season__c.object
<CustomObject>
    <fields>
        <fullName>TV_Serie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>TV Serie</label>
        <referenceTo>TV_Serie__c</referenceTo>
        <relationshipLabel>Seasons</relationshipLabel>
        <relationshipName>Seasons</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Season</label>
    <nameField>
        <displayFormat>season-{0000}</displayFormat>
        <label>Season Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

package/objects/TV_Serie__c.object
<CustomObject>
    <label>TV Serie</label>
    <nameField>
        <label>TV Serie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TvSerieControllerTest.cls
@isTest
public class TvSerieControllerTest {
        
    @isTest static void TestDeleteTvSerie() {
        List<Episode__c> episodes = new List<Episode__c>();
        List<Season__c> seasons = new List<Season__c>();
        List<TV_Serie__c> tvSeries = new List<TV_Serie__c>();

        // create tv serie and insert
        TV_Serie__c tv = TestDataFactory.getSimpleTvSerie('xD','https://www.google.pl','Description');
        insert tv;
        //create season and insert
        Season__c season = TestDataFactory.getSimpleSeason('Name',tv.Id);
        seasons.add(season);
        insert seasons;

        Review__c review = TestDataFactory.getSimpleReview(7, tv.Id);
        insert review;
        
        //create episodes and insert
        for(Integer i = 0; i< 100; i++) {
			episodes.add(TestDataFactory.getSimpleEpisode('Name'+i,seasons.get(0).Id, 'desc'));
        }
        insert episodes;
		
        Test.startTest();
 		TvSerieController.deleteTvSeries(tv.Id);
        Test.stopTest();
      	List<TV_Serie__c> testTvSerie = [SELECT Id FROM TV_Serie__c];
      	List<Season__c> testSeason = [SELECT Id FROM Season__c];
        List<Episode__c> testEpisode = [SELECT Id FROM Episode__c];
      	System.assertEquals(0,testTvSerie.size());
     	System.assertEquals(0,testSeason.size());
        System.assertEquals(0,testEpisode.size());

	}
}