package/objects/Episode__c.object
<CustomObject>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Episodes</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TV_Serie__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TV Serie</label>
        <referenceTo>TV_Serie__c</referenceTo>
        <relationshipLabel>Episodes</relationshipLabel>
        <relationshipName>Episodes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Episode</label>
    <nameField>
        <displayFormat>Episode-{0000}</displayFormat>
        <label>Episode Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Episodes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

package/objects/Review__c.object
<CustomObject>
    <fields>
        <fullName>TV_Serie__c</fullName>
        <label>TV Serie</label>
        <referenceTo>TV_Serie__c</referenceTo>
        <relationshipLabel>Reviews</relationshipLabel>
        <relationshipName>Reviews</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Review</label>
    <nameField>
        <displayFormat>review-{0000}</displayFormat>
        <label>Review Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

package/objects/Season__c.object
<CustomObject>
    <fields>
        <fullName>TV_Serie__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>TV Serie</label>
        <referenceTo>TV_Serie__c</referenceTo>
        <relationshipLabel>Seasons</relationshipLabel>
        <relationshipName>Seasons</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Season</label>
    <nameField>
        <displayFormat>season-{0000}</displayFormat>
        <label>Season Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

package/objects/TV_Serie__c.object
<CustomObject>
    <label>TV Serie</label>
    <nameField>
        <label>TV Serie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TV Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteEpisodeBatch.cls
global with sharing class DeleteEpisodeBatch implements Database.Batchable<sObject>,Database.Stateful {
    
   		 List<TV_Serie__c> episodes = new List<TV_Serie__c>();

	    global DeleteEpisodeBatch(List<TV_Serie__c> e) {	
        episodes = e;
    }
	
    global List<TV_Serie__c> start(Database.BatchableContext bc) {
        return episodes;
    }

    global void execute(Database.BatchableContext bc, List<TV_Serie__c> records) {
        List<Season__c> seasons = [SELECT Id from Season__c where TV_Serie__c =:records];
        List<Episode__c> episodes = [SELECT Id from Episode__c where Season__c =:seasons];
        List<Review__c> reviews = [SELECT Id from Review__c WHERE TV_Serie__c =:records];
        delete episodes;
        delete seasons;
        delete reviews;
        delete records;
    }

    global void finish(Database.BatchableContext bc){
    }
}